### ISSUE TITLE
Change the interval for triggering the motion

### ISSUE THREAD

**Issue by Deshmir** [gunnargestsson/homebridge-switch-to-sensor#1]
Is it possible to add the interval to the settings page? Instead of the fixed 5000?

or is it possible to just edit the files in node_modules and restarting homebridge?

(if its easy, i was also looking into some code to trigger the motion sensor multiple times, is that just copy paste?)

**Comment by gunnargestsson** [comment]
I am very likely to accept your pull request for code changes and build a new version.  Is that acceptable?

**Comment by gunnargestsson** [comment]
You need to add the configuration to the config.schema.json and then you should be able to use that value in code.

**Comment by gunnargestsson** [comment]
for example as this.platform.config.interval

**Comment by gunnargestsson** [comment]
I have done the update and new plugin package is available.
